#!/bin/sh

# below is copy-pasted from the emscripten manual

# Run emconfigure with the normal configure command as an argument.
# needed to manually add C++11 support
emconfigure ./configure CXXFLAGS="-std=c++03 -g -O2"


# Run emmake with the normal make to generate wasm object files.
emmake make

# Compile the linked code generated by make to JavaScript + WebAssembly.
# 'project.o' should be replaced with the make output for your project, and
# you may need to rename it if it isn't something emcc recognizes
# (for example, it might have a different suffix like 'project.so' or
# 'project.so.1', or no suffix like just 'project' for an executable).
# If the project output is a library, you may need to add your 'main.c' file
# here as well.
# [-Ox] represents build optimisations (discussed in the next section).
emcc [-Ox] project.o -o project.js
